#!/usr/bin/python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate reviewed Rust notices from cargo-about without exporting local Cargo paths."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent.parent


def export(data):
    files, packages = {}, {}
    for group in data['licenses']:
        used = [entry['crate'] for entry in group['used_by'] if entry['crate']['name'] != 'niri-bridge']
        if not used:
            continue
        content = group['text'].replace('\r\n', '\n').replace('\r', '\n').strip() + '\n'
        filename = re.sub('[^A-Za-z0-9.-]', '-', group['id']) + '-' + hashlib.sha256(content.encode()).hexdigest()[:16] + '.txt'
        files[filename] = content
        for crate in used:
            key = (crate['name'], crate['version'])
            row = packages.setdefault(key, {'name': crate['name'], 'version': crate['version'],
                'declared_license': crate.get('license'), 'repository': crate.get('repository'), 'notices': []})
            if filename not in row['notices']:
                row['notices'].append(filename)
    for row in packages.values():
        row['notices'].sort()
    for entry in data['crates']:
        crate = entry['package']
        key = (crate['name'], crate['version'])
        if key not in packages:
            continue
        root = Path(crate['manifest_path']).parent
        originals = []
        for source in root.rglob('*'):
            if source.is_file() and not source.is_symlink() and source.name.upper().startswith(('LICENSE', 'LICENCE', 'NOTICE', 'COPYRIGHT', 'COPYING')):
                name = 'upstream/' + crate['name'] + '-' + crate['version'] + '/' + source.relative_to(root).as_posix()
                content = source.read_text()
                files[name] = content
                originals.append(name)
        packages[key]['upstream_notices'] = sorted(originals)
    files['index.json'] = json.dumps({'target': 'x86_64-unknown-linux-gnu',
        'generator': 'cargo-about 0.9.2', 'packages': [packages[key] for key in sorted(packages)]},
        indent=2, sort_keys=True, ensure_ascii=False) + '\n'
    files['README.md'] = '''# Rust dependency notices

These files are generated by `python3 scripts/third_party.py`. The index maps
exact dependency versions to retained license and copyright notices.

Scope: the Linux x86_64 dependency graph, including build dependencies and
excluding development-only dependencies. License choices are in `about.toml`.
Local Cargo locations and other build-machine metadata are not exported.

Third-party copyright holders and their attribution details are retained as
required by their licenses. Do not edit generated license texts manually.
'''
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cargo-about', default='cargo-about')
    parser.add_argument('--check', action='store_true', help='Fail when checked-in notices differ; do not write files.')
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix='niri-bridge-licenses-') as directory:
        raw = Path(directory) / 'licenses.json'
        subprocess.run([args.cargo_about, 'generate', '--locked', '--fail', '--format', 'json', '--output-file', str(raw)], cwd=ROOT, check=True)
        files = export(json.loads(raw.read_text()))
    output = ROOT / 'licenses/rust'
    current = {p.relative_to(output).as_posix() for p in output.rglob('*') if p.is_file()} if output.exists() else set()
    different = {name for name, content in files.items() if not (output / name).is_file() or (output / name).read_text() != content}
    obsolete = current - files.keys()
    if args.check:
        if different or obsolete:
            parser.exit(1, 'Rust dependency notices are out of date. Regenerate and review them.\n')
    else:
        output.mkdir(parents=True, exist_ok=True)
        for name, content in files.items():
            (output / name).parent.mkdir(parents=True, exist_ok=True)
            (output / name).write_text(content)
        for name in obsolete:
            if name in ('README.md', 'index.json') or name.startswith('upstream/') or re.fullmatch(r'[A-Za-z0-9.-]+-[a-f0-9]{16}\.txt', name):
                (output / name).unlink()
            else:
                parser.exit(1, 'An unexpected file in the generated notices directory was preserved.\n')
    index = json.loads(files['index.json'])
    print(f'Rust license notices checked for {len(index["packages"])} dependency packages.')


if __name__ == '__main__':
    main()
